type LookingForType = 'Friendship' | 'Networking' | 'Support';
type SeedGender = 'female' | 'male' | 'other';

export type SeedUserData = {
  email: string;
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  about: string;
  jobTitle: string;
  company?: string;
  institution?: string;
  graduationYear?: number;
  homeCountry: string;
  currentProvince: string;
  currentCountry: string;
  currentCity: string;
  languages: string[];
  interests: string[];
  lookingFor: LookingForType[];
  dateOfBirth: string;
  gender: SeedGender;
  profileComplete: boolean;
};

/** Index in `seedUsers` of Lucia (hub): connected only to indices in `LUCIA_CONNECTED_TO_INDICES`. */
export const HUB_USER_INDEX = 0;
/** Index in `seedUsers` of the user who will have exactly 4 connections (Tomas: Lucia + three partners). */
export const FOUR_CONNECTIONS_USER_INDEX = 9;

/** Lucia (hub) is connected to these seed user indices only — must be length 9 for “9 connections”. */
export const LUCIA_CONNECTED_TO_INDICES: readonly number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9];

/**
 * Target pending *incoming* connection requests per seed user index (receiver).
 * Index 0 (Lucia): 9 — filled by senders 10–18 (not connected to her; Patricia 19 unused for that count).
 * Other indices: 0 for this graph. Pairs that already have a `Connection` or any `ConnectionRequest`
 * (either direction) are skipped.
 */
export const PENDING_INCOMING_REQUESTS_PER_USER_INDEX: readonly number[] = [
  9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

/** `blockerIdx` / `blockedIdx` refer to positions in `seedUsers` (same as connection graph indices). */
export const SEED_BLOCKS: readonly { blockerIdx: number; blockedIdx: number; reason: string }[] = [
  { blockerIdx: 1, blockedIdx: 9, reason: 'Seed: agreed to meet then went silent — prefer a clean break.' },
  { blockerIdx: 6, blockedIdx: 5, reason: 'Seed: crossed boundaries in chat.' },
  { blockerIdx: 4, blockedIdx: 3, reason: 'Seed: uncomfortable interaction at a meetup.' },
];

/**
 * Mock DMs between seed users. Pairs must be connected in the seeded graph **before** any blocks run.
 * Indices: 0 Lucia … 9 Tomas (core graph); 10–19 are extra profiles (no edges to Lucia in seed graph).
 */
export const SEED_MESSAGES: readonly { senderIdx: number; receiverIdx: number; content: string; read: boolean }[] = [
  { senderIdx: 0, receiverIdx: 1, content: 'Hey Mateo — still good for coffee Saturday?', read: true },
  { senderIdx: 1, receiverIdx: 0, content: 'Sí! 10am at Boxcar Social works for me.', read: true },
  { senderIdx: 0, receiverIdx: 1, content: 'Perfect, I will grab us a table.', read: false },
  { senderIdx: 1, receiverIdx: 0, content: 'Gracias Lucia, see you then.', read: false },
  { senderIdx: 2, receiverIdx: 0, content: 'Lucia, do you know a good GP in the west end?', read: true },
  { senderIdx: 0, receiverIdx: 2, content: 'Yes — I will DM you the clinic name.', read: true },
  { senderIdx: 2, receiverIdx: 0, content: 'That would mean a lot, thank you.', read: false },
  { senderIdx: 3, receiverIdx: 9, content: 'Tomas, quick question about EllisDon referrals?', read: true },
  { senderIdx: 9, receiverIdx: 3, content: 'Shoot — what do you need?', read: true },
  { senderIdx: 3, receiverIdx: 9, content: 'Mostly whether they hire bilingual PMs.', read: true },
  { senderIdx: 9, receiverIdx: 3, content: 'They do. I can intro you to someone on my team.', read: false },
  { senderIdx: 3, receiverIdx: 9, content: 'Legend — thank you.', read: false },
  { senderIdx: 5, receiverIdx: 0, content: 'Lucia, any board game nights coming up?', read: true },
  { senderIdx: 0, receiverIdx: 5, content: 'Snakes and Lattes on Thursday if you are free.', read: false },
  { senderIdx: 8, receiverIdx: 0, content: 'Hola Lucia — saw your post about the asado. Count me in!', read: true },
  { senderIdx: 0, receiverIdx: 8, content: 'Amazing — I will send details this weekend.', read: false },
];

export const seedUsers: SeedUserData[] = [
  {
    email: 'lucia.martinez@example.com',
    username: 'lucia_m',
    password: 'Password123',
    firstName: 'Lucia',
    lastName: 'Martinez',
    dateOfBirth: '1997-05-14',
    gender: 'female',
    about: 'Moved to Canada two years ago for work. Love exploring new cities and meeting people from back home.',
    jobTitle: 'UX Designer',
    company: 'Shopify',
    institution: 'Universidad de Buenos Aires',
    graduationYear: 2019,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Photography', 'Hiking', 'Cooking', 'Travel'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'mateo.gomez@example.com',
    username: 'mateo_g',
    password: 'Password123',
    firstName: 'Mateo',
    lastName: 'Gomez',
    dateOfBirth: '1995-11-02',
    gender: 'male',
    about: 'Software developer from Córdoba. Always up for asado and fútbol on weekends.',
    jobTitle: 'Software Engineer',
    company: 'RBC',
    institution: 'Universidad Nacional de Córdoba',
    graduationYear: 2017,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English', 'Portuguese'],
    interests: ['Sports', 'Gaming', 'Cooking', 'Technology'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'valentina.lopez@example.com',
    username: 'valentina_l',
    password: 'Password123',
    firstName: 'Valentina',
    lastName: 'Lopez',
    dateOfBirth: '1994-07-22',
    gender: 'female',
    about: 'Nurse practitioner passionate about healthcare and community. Miss my family in Mendoza but love my life here.',
    jobTitle: 'Nurse Practitioner',
    company: 'SickKids Hospital',
    institution: 'Universidad de Mendoza',
    graduationYear: 2016,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Yoga', 'Reading', 'Volunteering', 'Gardening'],
    lookingFor: ['Friendship', 'Support'],
    profileComplete: true,
  },
  {
    email: 'santiago.fernandez@example.com',
    username: 'santiago_f',
    password: 'Password123',
    firstName: 'Santiago',
    lastName: 'Fernandez',
    dateOfBirth: '1993-01-30',
    gender: 'male',
    about: 'Entrepreneur building a fintech startup. Relocated from Rosario. Always looking to connect with fellow Argentines.',
    jobTitle: 'Co-Founder & CEO',
    company: 'PayLatam',
    institution: 'Universidad Austral',
    graduationYear: 2015,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English', 'Italian'],
    interests: ['Technology', 'Running', 'Reading', 'Wine Tasting'],
    lookingFor: ['Networking', 'Friendship'],
    profileComplete: true,
  },
  {
    email: 'camila.ruiz@example.com',
    username: 'camila_r',
    password: 'Password123',
    firstName: 'Camila',
    lastName: 'Ruiz',
    dateOfBirth: '2001-09-08',
    gender: 'female',
    about: 'Graduate student researching climate science. From Buenos Aires, adjusting to Canadian winters!',
    jobTitle: 'Research Assistant',
    company: 'University of Toronto',
    institution: 'University of Toronto',
    graduationYear: 2026,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English', 'French'],
    interests: ['Science', 'Hiking', 'Photography', 'Cycling'],
    lookingFor: ['Friendship', 'Support'],
    profileComplete: true,
  },
  {
    email: 'nicolas.silva@example.com',
    username: 'nicolas_s',
    password: 'Password123',
    firstName: 'Nicolas',
    lastName: 'Silva',
    dateOfBirth: '1991-12-03',
    gender: 'male',
    about: 'Data analyst who loves board games and craft beer. Proud porteño living in the GTA.',
    jobTitle: 'Senior Data Analyst',
    company: 'TD Bank',
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Board Games', 'Technology', 'Cooking', 'Sports'],
    lookingFor: ['Friendship'],
    profileComplete: true,
  },
  {
    email: 'sofia.moreno@example.com',
    username: 'sofia_m',
    password: 'Password123',
    firstName: 'Sofia',
    lastName: 'Moreno',
    dateOfBirth: '1996-04-17',
    gender: 'female',
    about: 'Architect turned project manager. Love exploring art galleries and discovering hidden gems around Toronto.',
    jobTitle: 'Project Manager',
    company: 'AECOM',
    institution: 'Universidad de La Plata',
    graduationYear: 2018,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Arts & Culture', 'Photography', 'Travel', 'Theatre'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'joaquin.garcia@example.com',
    username: 'joaquin_g',
    password: 'Password123',
    firstName: 'Joaquin',
    lastName: 'Garcia',
    dateOfBirth: '1990-08-25',
    gender: 'male',
    about: 'Personal trainer and fitness enthusiast from Mar del Plata. Helping people get strong, one rep at a time.',
    jobTitle: 'Personal Trainer',
    company: 'GoodLife Fitness',
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Fitness', 'Running', 'Cooking', 'Music'],
    lookingFor: ['Friendship', 'Networking', 'Support'],
    profileComplete: true,
  },
  {
    email: 'martina.aguirre@example.com',
    username: 'martina_a',
    password: 'Password123',
    firstName: 'Martina',
    lastName: 'Aguirre',
    dateOfBirth: '1999-02-11',
    gender: 'female',
    about: 'Marketing professional and tango dancer. Bringing a little bit of Buenos Aires everywhere I go.',
    jobTitle: 'Marketing Manager',
    company: 'Scotiabank',
    institution: 'ITBA',
    graduationYear: 2020,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English', 'French'],
    interests: ['Dancing', 'Music', 'Fashion', 'Travel'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'tomas.perez@example.com',
    username: 'tomas_p',
    password: 'Password123',
    firstName: 'Tomas',
    lastName: 'Perez',
    dateOfBirth: '1989-06-19',
    gender: 'male',
    about: 'Recently arrived in Canada. Working in construction management and looking to meet people from home.',
    jobTitle: 'Construction Manager',
    company: 'EllisDon',
    institution: 'Universidad Tecnológica Nacional',
    graduationYear: 2014,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Sports', 'Camping', 'DIY Projects', 'Fishing'],
    lookingFor: ['Friendship', 'Support'],
    profileComplete: true,
  },
  {
    email: 'alejandro.vega@example.com',
    username: 'alejandro_v',
    password: 'Password123',
    firstName: 'Alejandro',
    lastName: 'Vega',
    dateOfBirth: '1994-10-05',
    gender: 'male',
    about: 'Civil engineer who moved to Mississauga last year. Still looking for a good yerba mate supplier.',
    jobTitle: 'Structural Engineer',
    company: 'WSP',
    institution: 'Universidad Nacional del Litoral',
    graduationYear: 2016,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Mississauga',
    languages: ['Spanish', 'English'],
    interests: ['Cycling', 'Cooking', 'Sports', 'Podcasts'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'florencia.diaz@example.com',
    username: 'florencia_d',
    password: 'Password123',
    firstName: 'Florencia',
    lastName: 'Diaz',
    dateOfBirth: '1997-03-28',
    gender: 'female',
    about: "Elementary school teacher from La Plata. Love kids' books and weekend trips to Niagara.",
    jobTitle: 'Teacher',
    company: 'Peel District School Board',
    institution: 'UNLP',
    graduationYear: 2019,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English', 'French'],
    interests: ['Reading', 'Hiking', 'Theatre', 'Volunteering'],
    lookingFor: ['Friendship', 'Support'],
    profileComplete: true,
  },
  {
    email: 'ricardo.soto@example.com',
    username: 'ricardo_s',
    password: 'Password123',
    firstName: 'Ricardo',
    lastName: 'Soto',
    dateOfBirth: '1988-07-14',
    gender: 'male',
    about: 'Electrician and weekend DJ. Trying to build a small studio in my basement.',
    jobTitle: 'Licensed Electrician',
    company: 'IESO Contractor',
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Hamilton',
    languages: ['Spanish', 'English'],
    interests: ['Music', 'DIY Projects', 'Sports', 'Podcasts'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'julia.romero@example.com',
    username: 'julia_r',
    password: 'Password123',
    firstName: 'Julia',
    lastName: 'Romero',
    dateOfBirth: '1998-11-09',
    gender: 'female',
    about: 'PhD student in neuroscience. Missing asados but not the humidity of BA summers.',
    jobTitle: 'Graduate Researcher',
    company: 'McMaster University',
    institution: 'McMaster University',
    graduationYear: 2027,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Hamilton',
    languages: ['Spanish', 'English'],
    interests: ['Science', 'Running', 'Chess', 'Movies'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'facundo.castro@example.com',
    username: 'facundo_c',
    password: 'Password123',
    firstName: 'Facundo',
    lastName: 'Castro',
    dateOfBirth: '1992-05-20',
    gender: 'male',
    about: 'Barista and aspiring roaster. Always happy to trade café tips with fellow porteños.',
    jobTitle: 'Head Barista',
    company: 'Pilot Coffee Roasters',
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English', 'Italian'],
    interests: ['Cooking', 'Cycling', 'Photography', 'Music'],
    lookingFor: ['Friendship'],
    profileComplete: true,
  },
  {
    email: 'carolina.navarro@example.com',
    username: 'carolina_n',
    password: 'Password123',
    firstName: 'Carolina',
    lastName: 'Navarro',
    dateOfBirth: '1995-08-01',
    gender: 'female',
    about: 'HR generalist at a tech startup. Organizing a Latinx professionals meetup in the GTA.',
    jobTitle: 'HR Business Partner',
    company: 'Wave Financial',
    institution: 'Universidad de Palermo',
    graduationYear: 2017,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Language Learning', 'Yoga', 'Travel', 'Cooking'],
    lookingFor: ['Networking', 'Friendship'],
    profileComplete: true,
  },
  {
    email: 'bruno.acosta@example.com',
    username: 'bruno_a',
    password: 'Password123',
    firstName: 'Bruno',
    lastName: 'Acosta',
    dateOfBirth: '1993-12-12',
    gender: 'male',
    about: 'Mechanic and rally fan. New to Ottawa, learning to skate like a true Canadian.',
    jobTitle: 'Automotive Technician',
    company: 'Canadian Tire',
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Ottawa',
    languages: ['Spanish', 'English'],
    interests: ['Sports', 'Outdoor Activities', 'Cooking', 'Gaming'],
    lookingFor: ['Friendship', 'Support'],
    profileComplete: true,
  },
  {
    email: 'elena.vargas@example.com',
    username: 'elena_v',
    password: 'Password123',
    firstName: 'Elena',
    lastName: 'Vargas',
    dateOfBirth: '1994-06-06',
    gender: 'female',
    about: 'Graphic designer freelancing for nonprofits. Collecting vintage posters from Latin America.',
    jobTitle: 'Freelance Designer',
    company: 'Self-employed',
    institution: 'UBA FADU',
    graduationYear: 2015,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Drawing', 'Museum Visits', 'Swimming', 'Travel'],
    lookingFor: ['Friendship', 'Networking'],
    profileComplete: true,
  },
  {
    email: 'diego.morales@example.com',
    username: 'diego_m',
    password: 'Password123',
    firstName: 'Diego',
    lastName: 'Morales',
    dateOfBirth: '1987-04-03',
    gender: 'other', // Kept distinct from 'female'/'male' so QA can verify gender = 'other' rendering
    about: 'Warehouse lead by day, guitar by night. Tango classes on Tuesdays in the west end.',
    jobTitle: 'Warehouse Supervisor',
    company: 'Amazon',
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Music', 'Dancing', 'Sports', 'Cooking'],
    lookingFor: ['Friendship'],
    profileComplete: true,
  },
  {
    email: 'patricia.flores@example.com',
    username: 'patricia_f',
    password: 'Password123',
    firstName: 'Patricia',
    lastName: 'Flores',
    dateOfBirth: '1960-01-15',
    gender: 'female',
    about: 'Retired accountant, now volunteering with newcomers. Grandkids keep me on FaceTime daily.',
    jobTitle: 'Volunteer Tax Preparer',
    company: 'Community Centre',
    institution: 'Universidad de Buenos Aires',
    graduationYear: 1988,
    homeCountry: 'Argentina',
    currentProvince: 'Ontario',
    currentCountry: 'Canada',
    currentCity: 'Toronto',
    languages: ['Spanish', 'English'],
    interests: ['Volunteering', 'Gardening', 'Outdoor Activities', 'Reading'],
    lookingFor: ['Support', 'Friendship'],
    profileComplete: true,
  },
];
