import fs from 'node:fs';
import path from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';
import { loadEnv } from 'vite';

/** Keep in sync with major firebase package used in the app (compat scripts on gstatic). */
const FIREBASE_COMPAT_VERSION = '11.10.0';

const buildServiceWorkerSource = (env: Record<string, string>): string => {
    const firebaseConfig: Record<string, string> = {
        apiKey: env.VITE_FIREBASE_API_KEY ?? '',
        authDomain: env.VITE_FIREBASE_AUTH_DOMAIN ?? '',
        projectId: env.VITE_FIREBASE_PROJECT_ID ?? '',
        storageBucket:
            env.VITE_FIREBASE_STORAGE_BUCKET ??
            (env.VITE_FIREBASE_PROJECT_ID ? `${env.VITE_FIREBASE_PROJECT_ID}.appspot.com` : ''),
        messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? '',
        appId: env.VITE_FIREBASE_APP_ID ?? '',
    };
    const mid = env.VITE_FIREBASE_MEASUREMENT_ID?.trim();
    if (mid) firebaseConfig.measurementId = mid;

    return `/* Generated by Vite (plugins/firebaseMessagingSw.ts) — do not edit by hand */
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_COMPAT_VERSION}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${FIREBASE_COMPAT_VERSION}/firebase-messaging-compat.js');

const firebaseConfig = ${JSON.stringify(firebaseConfig)};

if (firebaseConfig.apiKey) {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    const title = payload.notification?.title || 'KinMeet';
    const body = payload.notification?.body || '';
    const data = payload.data || {};
    const options = {
      body,
      icon: '/KinmeetLogo.png',
      badge: '/KinmeetLogo.png',
      tag: data.messageId ? String(data.messageId) : 'kinmeet-chat',
      data: {
        clickPath: data.clickPath ? String(data.clickPath) : '/discover',
      },
    };
    return self.registration.showNotification(title, options);
  });
}

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const rawPath = event.notification.data?.clickPath || '/discover';
  const urlToOpen = new URL(rawPath, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.startsWith(self.location.origin) && 'focus' in client) {
          const c = client;
          if ('navigate' in c && typeof (c).navigate === 'function') {
            void (c).navigate(urlToOpen);
          }
          return c.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    }),
  );
});
`;
};

export const firebaseMessagingSwPlugin = (): Plugin => {
    let viteConfig: ResolvedConfig;

    return {
        name: 'firebase-messaging-sw',
        configResolved(config) {
            viteConfig = config;
        },
        buildStart() {
            const env = loadEnv(viteConfig.mode, viteConfig.root, 'VITE_');
            const outPath = path.join(viteConfig.root, 'public', 'firebase-messaging-sw.js');
            fs.mkdirSync(path.dirname(outPath), { recursive: true });
            fs.writeFileSync(outPath, buildServiceWorkerSource(env), 'utf8');
        },
    };
};
